### ISSUE TITLE
Separate productization process

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye#22]
The product builds of SmallRye are currently performed as part of Thorntail product work.

We need to separate it into its own set of builds so that we can spin new versions at any time for Thorntail, EAP, or Quarkus.

We also need to document the process for everyone

**Comment by Ladicek** [comment]
I believe this was sufficiently addressed, though there are some improvements still planned/ongoing. Let's close this -- if anyone disagrees, we can easily reopen.

Also would like to honourably mention that @jmartisk has done a lot of work there! :-)
