### ISSUE TITLE
Define MP TCK Challenge process

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye#42]
Informally it's understood and accepted that an implementation can still claim it passes the TCK while excluding a number of tests that are currently being challenged through issues in the specification.

It would be good to formally define the TCK challenge process and the implications around compatibility.

**Comment by radcortez** [comment]
I believe with the WG in place, this does not apply anymore. The API and Spec have to indicate a compatible implementation, meaning that TCK challenges and issues will need to be resolved before any release.

**Comment by kenfinnigan** [comment]
I don't agree.

The requirement to have a compatible implementation present before API/Spec/TCK are released has always been the case.

This issue was around a non compatible implementation challenging an existing TCK test saying that it's invalid, inaccurate, or whatever.

It also ties into whether an MP implementation can claim "compatibility" while a TCK challenge is underway

**Comment by radcortez** [comment]
Ok, I guess I misunderstood the issue description.

**Comment by radcortez** [comment]
This is now being addressed here:
https://github.com/microprofile/microprofile-wg/pull/96
